# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170719_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'ordering': ['order'], 'verbose_name_plural': 'Ticket priorities'},
        ),
        migrations.AlterModelOptions(
            name='ticketproblem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'ordering': ['order'], 'verbose_name_plural': 'Ticket statuses'},
        ),
        migrations.AddField(
            model_name='ticketpriority',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketproblem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
