# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20170719_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigend to'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.TicketPriority', verbose_name='Ticket priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.TicketProblem', verbose_name="I'm having a problem with"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.TicketStatus', verbose_name='Ticket status'),
        ),
    ]
