# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20170720_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.TicketStatus', verbose_name='Ticket status'),
        ),
    ]
