# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20170720_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigend to'),
        ),
    ]
