# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20170720_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Describe your problem'),
        ),
    ]
